name: "Release and Deploy"
on:
  push:
    branches:
      - "master"

jobs:
  release-and-deploy:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 60
    permissions:
      actions: write
      contents: write
      id-token: write
      pages: write
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@v15
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/flake-checker-action@v9

      - name: "Set up git user email"
        run: >
          nix develop --command
          git config --global user.email 'maciej.laciak@gmail.com'

      - name: "Set up git user name"
        run: >
          nix develop --command
          git config --global user.name 'mstream'

      - name: "Run e2e tests"
        run: >
          ./scripts/test.ts

      - name: "Create a GitHub release"
        run: >
          nix develop -c 
          npm run release -- --ci
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Deploy to GitHub Pages"
        uses: "peaceiris/actions-gh-pages@v4"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./dist"
