name: "Release and Deploy"
on:
  push:
    branches:
      - "master"

jobs:
  release-and-deploy:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@v15
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/flake-checker-action@v9

      - name: "Set up git user email"
        run: >
          nix develop --command
          git config --global user.email 'maciej.laciak@gmail.com'

      - name: "Set up git user name"
        run: >
          nix develop --command
          git config --global user.name 'mstream'

      - name: "Run e2e tests"
        run: >
          ./scripts/test.ts
